spring:
  application:
    name: crm
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: UTC
  docker:
    compose:
      file: deploy/docker-compose.dev.yml
      lifecycle-management: start_only
  profiles:
    default: dev

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: test
  docker:
    compose:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  docker:
    compose:
      enabled: false
