package com.kpi.studentcouncil.crm.files.internal;

import java.io.IOException;
import java.io.InputStream;

/**
 * Where file bytes live. The local-disk implementation is {@link LocalFileStorage}; an S3/MinIO implementation can
 * be added later without touching callers. Keys are opaque, generated by {@link StorageKeys}, never derived from
 * user-supplied names.
 */
public interface FileStorage {

	/**
	 * Stores the stream under the key and returns the number of bytes written. A failure (including an exception
	 * thrown by the stream) must leave nothing behind under the key.
	 */
	long store(String key, InputStream content) throws IOException;

	/** Opens the stored bytes; throws {@link java.io.FileNotFoundException} if the key is unknown. */
	InputStream open(String key) throws IOException;

	/** Removes bytes; used only to roll back a failed upload, never for user-initiated deletion. */
	void remove(String key) throws IOException;

}
